Update code from week1 to week2, a backend service that provides create and search users service
joshtu0627/remote-assignments pull request #3
Opened 2023-10-02 16:00 UTC by joshtu0627

IP: http://13.236.23.10
(port 為 80，因為是預設 http port，不用加)

Routes: /healthcheck, /users, /users/:id

Database name: assignment

Change summary :

**because week2 assignment is completly different from last commit in main branch (week1 assignment), so I put features of the code here**

- create connection to database
- add health check route
- add get all users route
- add query user id route
- add create user route

# Understanding Check

1. How did you design the user table schema? Why?
    ![image](https://github.com/joshtu0627/remote-assignments/assets/60171069/d6ce8f34-bfae-4447-a1a8-b8212aec5f16)

- id: 由於 id 是唯一的，且可以自動生成，所以使用 int auto_increment
- name: 使用 varchar，因為 name 是字串，且長度不確定，也不能為空，所以使用 varchar not null
- email: 與 name 相同，使用 varchar not null，且由於 email 在我們的作業描述中需要是唯一的，所以使用 unique
- password: 使用 varchar not null，因為 password 存的是 hash 過後的字串，所以長度不確定，且不能為空
- created_at: 使用 Datetime，因為 created_at 是時間，我認為此欄位可以為空，所以不使用 not null

2. What does the status code mean? Is it a must to use?

   status code 是用來表示伺服器回應的狀態，例如 200 表示成功，404 表示找不到資源。不一定要用 status code，但是大部分情況下使用 status code 可以更明確的讓客戶端了解請求的結果。

3. How and what tools did you use to test your APIs?

   我用一個靜態網頁使用 fetch 來測試 api，模擬出真正的使用情境。

4. How and what tools did you use to make sure the app would not shut down even if you exit the ssh connection?

   我使用一個叫做 forever 的套件，可以讓 nodejs 程式在背景執行，即使關閉 ssh 連線也不會停止。

5. What are the interactions between client, firewall, EC2 and RDS when you send a request to you app server and get the response? You can use sequence diagram to describe it more clearly

   System Architecture
  ![image](https://github.com/joshtu0627/remote-assignments/assets/60171069/e0b73bb3-7a03-47f0-beb1-54b1c1636cb7)

   The interactions between client, firewall, EC2 and RDS
  ![image](https://github.com/joshtu0627/remote-assignments/assets/60171069/2b79885d-3748-4bce-b1c1-92841a8426a9)

6. (advanced optional) What did you do to make clients access your APIs without the certain port number?

   可以把 server 的 port 設定為 http 默認的 port 80，這樣就不用在網址後面加上 port number。

7. (advanced optional) Compare to the application server, what's the web server?

   Web server 負責與 client 之間的溝通，例如接收 client 的請求，並回傳靜態資料給 client。

   Application server 則是負責處理 Webserver 傳來的請求，並回傳處理後的結果，例如處理業務邏輯，以及資料庫的 CRUD 等等。

# Recap

1. How can others know your dependencies if we don't upload the node_modules? What's the differences between devDependencies and dependencies?

   package.json 會記錄專案的 dependencies，其他人在 clone 專案後，只要執行 npm install，就會自動安裝 dependencies。

   devDependencies 是開發時才需要的 dependencies，例如測試套件，或是編譯器等等，而 dependencies 則是在執行時才需要的 dependencies，例如 express，mysql 等等。

2. Is it safe to commit the database password to GitHub? How should we keep the confidential and sensitive data？

   不安全，可以把敏感資料放在.env 檔案中，並且加入.gitignore，這樣就不會被上傳到 github。

   在此專案中有實作這個部分。

3. Could we save the users' passwords by plain code? How should we store users' passwords safely in the database?

   不可以，因為如果資料庫被駭客入侵，駭客就可以直接看到使用者的密碼。

   我們可以使用 hash function，將密碼 hash 過後再存入資料庫，這樣即使資料庫被駭客入侵，駭客也無法直接看到使用者的密碼。

   此專案中有使用 bcrypt 函式庫實作這個部分。

2023-10-03 02:28 UTC, addie-tyc requested changes
1. 在 .gitignore 裡面加上 node_modules 沒錯！但因為前一次 node_modules 已經被 commit 了，有沒有什麼 git 的操作可以把已經被 commit 的檔案也移除掉呢？
2. 你是如何讓 app 跑在 port 80 的呢？

2023-10-03 03:10 UTC, joshtu0627 commented
1. 是否可以使用git reset來回退一次commit再重新push去除掉檔案的版本?
2. 我在開啟伺服器時使用sudo來確保有開啟port 80伺服器的權限

2023-10-03 03:53 UTC, addie-tyc commented
1. 這個方法 ok 可以試試看
2. ok，用 sudo 執行 app server 會產生什麼問題嗎？

2023-10-03 04:38 UTC, joshtu0627 commented
1. 了解！
2. 用sudo執行server似乎會有安全問題，如果伺服器有漏洞，駭客可以有root權限的系統控制權。
在不用sudo的port中建server後，把80 port的request導到那個port感覺應該是比較安全的選擇。

2023-10-07 08:39 UTC, addie-tyc approved these changes
LGTM

2023-10-07 09:43 UTC, merged